import Fonts from '@/constants/fonts'
import './globals.css'

import { RTKProvider } from '@/providers/Redux'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={["scroll-minimalist overscroll-none font-poppins", Fonts.className].join(" ")}>
        <RTKProvider>
          {children}
        </RTKProvider>
      </body>
    </html>
  )
}
